CREATE TABLE IF NOT EXISTS engines (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  engine_name VARCHAR(200) NOT NULL,
  engine_path VARCHAR(200) NOT NULL,
  is_default INTEGER NOT NULL DEFAULT 0
);