name: Node.js CI

on: [push, pull_request]

jobs:
  tests:
    name: Run Tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [19.x, 18.x, 16.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: setup npm
        run: npm ci
      - name: check code style
        run: npm run lint
      - name: run type checks
        run: npm run type-check
      - name: test build process
        run: npm run build
